version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sse_go
    ports:
      - 8080:8080
    volumes:
      - .:/app/
    command: go run cmd/main.go
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_WHOST=/
